version: '3.9'

services:

  media:
    container_name: media
    env_file:
      - .\cmd\main\.env
    environment:
        - API_ADDRESS=media:8082
        - S3_ADDRESS=minio:9000
        - S3_ACCESS_KEY=accesskey
        - S3_SECRET_KEY=secretkey
        - S3_BUCKET=media
        - S3_POLICY_FILE=./s3-policy.json
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - minio
    restart: unless-stopped
    networks:
      - s3

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    command: server /data
    volumes:
      - minio-data:/data
    networks:
      - s3

volumes:
  minio-data:

networks:
  s3:
    driver: bridge